### ISSUE TITLE
Training time and Processor??

### ISSUE THREAD

**Issue by 3timesv** [tuandoan998/Handwriting-OCR#1]
How did you trained it , On CPU or GPU? And how long it take to train this model?

**Comment by tuandoan998** [comment]
> How did you trained it , On CPU or GPU? And how long it take to train this model?

I train it on Google Colab with GPU. It takes about 8 hours for each model.

**Comment by 3timesv** [comment]
You wrote any additional command for GPU or Colab automatically recognizes which operations to run on GPU??

**Comment by tuandoan998** [comment]
I just choose GPU in Notebook settings.

**Comment by 3timesv** [comment]
Thanks you have done great project it really helped me :)

**Comment by naveenmarthala** [comment]
Mr.@tuandoan998, How did you manage to keep the colab session active for 8 hours?

**Comment by tuandoan998** [comment]
@naveen-kumar-123 
Keeping colab always enabled, that's just the prerequisite. You can see this way - https://stackoverflow.com/questions/57113226/how-to-prevent-google-colab-from-disconnecting
