### ISSUE TITLE
'K' is not defined

### ISSUE THREAD

**Issue by AICampB4** [tuandoan998/Handwriting-OCR#4]
![image](https://user-images.githubusercontent.com/91046245/141247933-e02fc46c-6f3d-49dc-a2d1-5f32e93dcf76.png)

 Hi author, there is something wrong when I run Prediction.py or Evaluation.py. A few days ago, the code had been working well until this bug suddenly appeared from nowhere, I dind't change anything in the code. Hope you help to to define this problem.

**Comment by tuandoan998** [comment]
The version of Keras I used belongs to Tensorflow 1.x.
The simplest way you can continue using this Repo is to use Tensorflow 1.x ("%tensorflow_version 1.x" with Google Colab).
Or you can modify the code to be compatible with Tensorflow 2.x.
